OUTPUT_DIR: "./checkpoints/cityscapes/e2e_lr_mask_rcnn_depth_R_50_FPN_depthnet_FPN_1x_cocoft"
MODEL:
  META_ARCHITECTURE: "GeneralizedLRRCNN"
  WEIGHT: "checkpoints/pretrained/e2e_mask_rcnn_R_50_FPN_1x_cityscapes.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN-DEPTHNET-FPN"
    # FREEZE_CONV_BODY_AT: 5
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  # FPN:
    # FREEZE_WEIGHT: True
  DEPTHNET_ON: True
  DEPTHNET:
    DECODER_COARSE_TO_FINE: True
    LOSS_IMAGE: 0.01
    LOSS_LR_CONSISTENCY: 0.01
    LOSS_SMOOTHNESS: 0.01
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    # FREEZE_WEIGHT: True
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 9
    # OUTPUT_DECODED_PROPOSAL: True
    # FREEZE_WEIGHT: True
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
    # FREEZE_WEIGHT: True
  MASK_ON: True # disable mask to reduce memory usage
  ROI_DEPTH_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNDepthPredictor"
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
    SHARE_BOX_FEATURE_EXTRACTOR: False
    REG_AMPLIFIER: 20.0
    # LR_REGULARIZATION_AMPLIFIER: 10.0
    # FREEZE_WEIGHT: True
  DEPTH_ON: True
INPUT:
  MIN_SIZE_TRAIN: (800, 832, 864, 896, 928, 960, 992, 1024, 1024) #
  MAX_SIZE_TRAIN: 2048
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 2048
  LR_IMAGE: True
  # RANDOM_TRANSLATE: (-0.1, 0.1)
  # RANDOM_SCALE: (0.8, 1.2)
DATASETS:
  TRAIN: ("cityscapes_fine_instanceonly_seg_lr_train",)
  TEST: ("cityscapes_fine_instanceonly_seg_lr_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  IMS_PER_BATCH: 2
  WEIGHT_DECAY: 0.0001
  STEPS: (15000,)
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 5000
