OUTPUT_DIR: "./checkpoints/cityscapes/e2e_multidataset_mt_mask_rcnn_depth_R_50_FPN_1x_cocoft"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "checkpoints/pretrained/e2e_mask_rcnn_R_50_FPN_1x_cityscapes.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    # FREEZE_CONV_BODY_AT: 5
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  # FPN:
    # FREEZE_WEIGHT: True
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    # FREEZE_WEIGHT: True
  ROI_HEADS:
    USE_FPN: True
    # SCORE_THRESH: 0.0
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 4
    # OUTPUT_DECODED_PROPOSAL: True
    # FREEZE_WEIGHT: True
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
    # FREEZE_WEIGHT: True
  MASK_ON: True
  ROI_DEPTH_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNDepthPredictor"
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
    SHARE_BOX_FEATURE_EXTRACTOR: False
    # LOSS_AMPLIFIER: 0.01
    REG_AMPLIFIER: 50.0
    # FREEZE_WEIGHT: True
  DEPTH_ON: True
  MT:
    FEATURE_CONSISTENCY_WEIGHT: 1.0
    RPN_LOGITS_FROM_STUDENT_FEATURE: True
    RPN_LOGITS_CONSISTENCY_WEIGHT: 1.0
    ROI_LOGITS_FROM_STUDENT_FEATURE: True
    ROI_LOGITS_CONSISTENCY_WEIGHT: 1.0
  MT_ON: True
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 2048
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 2048
  # RANDOM_TRANSLATE: (-0.01, 0.01)
  # RANDOM_SCALE: (0.8, 1.2)
# TEST:
#   INPUT_TARGETS: True
#   TARGETS_AS_PROPOSALS: True
DATASETS:
  TRAIN: ("cityscapes_fine_instanceonly_seg_wd_train", "")
  TEST: ("cityscapes_fine_instanceonly_seg_wd_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  IMS_PER_BATCH: 3
  WEIGHT_DECAY: 0.0001
  STEPS: (10000,13000)
  MAX_ITER: 15000
  CHECKPOINT_PERIOD: 5000
TRAINER:
  TYPE: "mt"
  MT:
    CONSISTENCY_RAMPUP: 1000
    CONSISTENCY_WEIGHT: 5
    EMA_DECAY: 0.999
    # EMA_DECAY_START: 1000
    # EMA_DECAY_WARMUP: 10000

