
OUTPUT_DIR: "./checkpoints/dukemtmc/e2e_mask_rcnn_depth_R_50_FPN_1x_depthonly_2"
INPUT:
  MIN_SIZE_TRAIN: (540,)
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://Caffe2Detectron/COCO/35858933/e2e_mask_rcnn_R-50-FPN_1x"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    FREEZE_CONV_BODY_AT: 5
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  FPN:
    FREEZE_WEIGHT: True
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    FREEZE_WEIGHT: True
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    FREEZE_WEIGHT: True
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
    FREEZE_WEIGHT: True
  MASK_ON: True
  ROI_DEPTH_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNDepthPredictor"
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
    SHARE_BOX_FEATURE_EXTRACTOR: False
  DEPTH_ON: True
DATASETS:
  TRAIN: ("dukemtmc_train_cocostyle",)
  TEST: ("dukemtmc_val_cocostyle",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  GAMMA: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (20000,40000)
  MAX_ITER: 50000
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 10000
