OUTPUT_DIR: "./checkpoints/kitti/e2e_lr_rpn_mask_rcnn_depth_from_3d_R_50_FPN_1x_cocoft_20"
MODEL:
  META_ARCHITECTURE: "GeneralizedLRRCNN"
  WEIGHT: "checkpoints/pretrained/e2e_mask_rcnn_R_50_FPN_1x_kitti.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    # FREEZE_CONV_BODY_AT: 5
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  # FPN:
    # FREEZE_WEIGHT: True
  RPN:
    USE_FPN: True
    RPN_HEAD: "SingleConvRPNLRHead"
    ANCHOR_SIZES: (16, 32, 64, 128, 256)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    # FREEZE_WEIGHT: True
  # RPN_LR:
  #   MONO_HEAD_TEST: True
  #   MONO_HEAD_ON: True
  #   LOSS_HEAD_CONSISTENCY: 1.0
  USE_LR_RPN: True
  ROI_HEADS:
    USE_FPN: True
  # ROI_HEADS_LR:
  #   MONO_HEAD_TEST: True
  #   MONO_HEAD_ON: True
  #   LOSS_FEATURE_CONSISTENCY: 1.0
  #   LOSS_PREDICTOR_CONSISTENCY: 1.0
  USE_LR_ROI_HEADS: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 4
    # OUTPUT_DECODED_PROPOSAL: True
    # FREEZE_WEIGHT: True
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
    # FREEZE_WEIGHT: True
  # MASK_ON: True # disable mask to reduce memory usage
  ROI_DEPTH_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "FPN2MLPLevelMix3DConvFeatureExtractor"
    FEATURE_EXTRACTOR_LR: "FPN2MLPLevelMixCostVolumeLRFeatureExtractor"
    USE_LR_FEATURE_EXTRACTOR: True
    PREDICTOR: "FPNDepthPredictor"
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
    SHARE_BOX_FEATURE_EXTRACTOR: False
    LOSS_AMPLIFIER: 2.0
    # INPUT_BOX_FEATURES: True
    DEPTH_FROM_LR_DETECTION: True
    # LR_REGULARIZATION_AMPLIFIER: 10.0
    # FREEZE_WEIGHT: True
  DEPTH_ON: True
INPUT:
  MIN_SIZE_TRAIN: (384,)
  # MAX_SIZE_TRAIN: 1224
  MIN_SIZE_TEST: 384
  # MAX_SIZE_TEST: 1224
  LR_IMAGE: True
  # RANDOM_TRANSLATE: (-0.01, 0.01)
  # RANDOM_SCALE: (0.8, 1.2)
  HORIZONTAL_FLIP_PROB_TRAIN: 0.0
# TEST:
#   INPUT_TARGETS: True
DATASETS:
  TRAIN: ("kitti_lr_3d_3dop_depth_from_3d_brfd_train",)
  TEST: ("kitti_lr_3d_3dop_depth_from_3d_brfd_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  # LOAD_OPTIMIZER_FROM_WEIGHT: False
  # LOAD_SCHEDULER_FROM_WEIGHT: False
  BASE_LR: 0.01
  IMS_PER_BATCH: 7
  WEIGHT_DECAY: 0.0001
  STEPS: (15000,)
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 5000
# TRAINER:
#   TYPE: "lr"