OUTPUT_DIR: "./checkpoints/kitti/e2e_mask_rcnn_depth_R_50_FPN_1x_cocoft"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "checkpoints/pretrained/e2e_mask_rcnn_R_50_FPN_1x_cityscapes.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    # FREEZE_CONV_BODY_AT: 5
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  # FPN:
    # FREEZE_WEIGHT: True
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    # FREEZE_WEIGHT: True
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 9
    # OUTPUT_DECODED_PROPOSAL: True
    # FREEZE_WEIGHT: True
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
    FREEZE_WEIGHT: True
  # MASK_ON: True
  ROI_DEPTH_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNDepthPredictor"
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
    SHARE_BOX_FEATURE_EXTRACTOR: False
    # REG_LOGARITHM: True
    REG_AMPLIFIER: 0.1
    # LOSS_AMPLIFIER: 0.005
    # FREEZE_WEIGHT: True
  DEPTH_ON: True
INPUT:
  MIN_SIZE_TRAIN: (370,)
  MAX_SIZE_TRAIN: 1224
  MIN_SIZE_TEST: 370
  # MAX_SIZE_TEST: 1224
DATASETS:
  TRAIN: ("kitti_3d_3dop_box3d_train",)
  TEST: ("kitti_3d_3dop_box3d_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  IMS_PER_BATCH: 16
  WEIGHT_DECAY: 0.0001
  STEPS: (10000,)
  MAX_ITER: 15000
  CHECKPOINT_PERIOD: 5000
